language: node_js
os: 
- linux
dist: xenial
node_js:
- '12'
script: 
- npm test
- npm build
deploy: 
  provider: heroku
  app: marvel-search-heroes
  on: 
    branch: main
  api_key:
    secure: dba8a8fb-bc8a-4ba4-abd6-dfb58bce62ec